site_name: Machine Learning Evaluation Kit (MLEK) for CMSIS Workflows
repo_url: https://github.com/ARM-Examples/cmsis-mlek
edit_uri: ./edit/main/docs
nav:
    - Home: index.md
    - Overview: overview.md
    - MLEK - Audio Applications: templates_audio.md
    - MLEK - Video Applications: templates_video.md
    - Targeting Hardware Boards: target_configuration_refapp.md
    - Targeting Arm Virtual Hardware: target_configuration_avh.md

plugins:
    - search
   # - mermaid2    # pip install mkdocs-mermaid2-plugin

theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
use_directory_urls: false
