name: Build documentation and pack
on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  release:
    types: [published]

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch tags
        if: ${{ github.event_name == 'release' }}
        run: |
          git fetch --tags --force

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install MkDocs
        run: |
          pip install mkdocs
          pip install mkdocs-mermaid2-plugin

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:

          doxygen-version: 1.13.2 
          packchk-version: 1.4.3
          gen-pack-script: ./gen_pack.sh
          gen-pack-output: ./output
          #gen-doc-script: ./docs/gen_doc.sh
          #doc-path: ./docs

      - name: Cache artifact
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/output
          key: latest-cmsis-mlek-pack
