# SPDX-FileCopyrightText: Copyright 2022-2025 Arm Limited and/or its
# affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: MLEK video build and execution test
on:

  workflow_dispatch:
  #pull_request:
  #  branches: [main]
  #push:
  #  branches: [main]
  #schedule:
  #  - cron: '00 20 * * 6'


jobs:
  CI:
    strategy:
      matrix:
        context: [
          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-300,      model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-300,      model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-300,      model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-300,      model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-300-U55,  model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-300-U55,  model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-300-U55,  model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-300-U55,  model: FVP_Corstone_SSE-300_Ethos-U55,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-300-U65,  model: FVP_Corstone_SSE-300_Ethos-U65,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-300-U65,  model: FVP_Corstone_SSE-300_Ethos-U65,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-300-U65,  model: FVP_Corstone_SSE-300_Ethos-U65,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-300-U65,  model: FVP_Corstone_SSE-300_Ethos-U65,  fvp_dir: Corestone-300,  fvp_cfg: fvp_config.txt,      mps: mps3},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-310,      model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-310,      model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-310,      model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-310,      model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-310-U55,  model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-310-U55,  model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-310-U55,  model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-310-U55,  model: FVP_Corstone_SSE-310,            fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-310-U65,  model: FVP_Corstone_SSE-310_Ethos-U65,  fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-310-U65,  model: FVP_Corstone_SSE-310_Ethos-U65,  fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-310-U65,  model: FVP_Corstone_SSE-310_Ethos-U65,  fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-310-U65,  model: FVP_Corstone_SSE-310_Ethos-U65,  fvp_dir: Corestone-310,  fvp_cfg: fvp_config.txt,      mps: mps3},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-315,      model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-315,      model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-315,      model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-315,      model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-315-U65,  model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-315-U65,  model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-315-U65,  model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-315-U65,  model: FVP_Corstone_SSE-315,            fvp_dir: Corestone-315,  fvp_cfg: fvp_config.txt,      mps: mps4},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-320,      model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-320,      model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-320,      model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-320,      model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4},

          {proj: object-detection,  build_type: Release-Live_Stream,  target_type: AVH-SSE-320-U85,  model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Live_Stream,    target_type: AVH-SSE-320-U85,  model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Release-Data_Array,   target_type: AVH-SSE-320-U85,  model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4},
          {proj: object-detection,  build_type: Debug-Data_Array,     target_type: AVH-SSE-320-U85,  model: FVP_Corstone_SSE-320,            fvp_dir: Corestone-320,  fvp_cfg: fvp_config.txt,      mps: mps4}
        ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
       sparse-checkout: .ci

    - name: Restore Latest Pack Build from Cache
      uses: actions/cache/restore@v4
      with:
         path: ${{ github.workspace }}/output
         key: latest-cmsis-mlek-pack

    - name: Extract pack content
      run: |
        mkdir -p ./ARM/cmsis-mlek/
        unzip ${{ github.workspace }}/output/ARM.CMSIS-MLEK.*.pack -d ./ARM/cmsis-mlek/

    - name: Install tools
      uses: ARM-software/cmsis-actions/vcpkg@v1
      with:
        config: ".ci/vcpkg-configuration.json"

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Initialize CMSIS pack root folder
      run: |
        cpackget init https://www.keil.com/pack/index.pidx
        cpackget update-index

    - name: Cache downloaded packs
      uses: actions/cache@v4
      with:
        key: cmsis-mlek-download
        path: /home/runner/.cache/arm/packs/.Download

    - name: AC6-Build-Test 4 context ${{matrix.context.proj}}.${{matrix.context.build_type}}+${{matrix.context.target_type}}
      working-directory: ./ARM/cmsis-mlek/template/video
      run: |
        cbuild mlek_video.csolution.yml --update-rte --packs --no-schema-check \
        --context ${{matrix.context.proj}}.${{matrix.context.build_type}}+${{matrix.context.target_type}} \
        --toolchain AC6 --rebuild